version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynet

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./server/nginx6/nginx.conf:/etc/nginx/nginx.conf:rw
    depends_on:
      - app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    